spring.application.name=studygram

spring.datasource.url=jdbc:mysql://localhost:3306/studygram
spring.datasource.username=root
spring.datasource.password=Yash5290

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true